use_frameworks!

platform :ios, '13.0'

target 'UPennMobileComponentsSDK_Example' do
  pod 'UPennMobileComponentsSDK', :path => '../'

  target 'UPennMobileComponentsSDK_Tests' do
    inherit! :search_paths

    
  end
end
